<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by www.codechief.org</title>
</head>
<body>
    <h1>{{ $comment['name'] }}</h1>
    <p>{{ $comment['body'] }}</p>
    <p>{{ $comment['team'] }}</p>
    <a href="{{ $comment['url'] }}"><p>Click here</p></a>
    <p>{{ $comment['urlname'] }}</p>

    <p>Thank you</p>
</body>
</html>
